<?php

namespace App\Actions\Jubelio;

use App\Models\Addrbook;
use App\Models\Item;
use App\Models\Jubelioorder;
use App\Models\Jubeliosync;
use App\Models\Transaction;
use App\Models\TransactionDetail;
use App\Services\JubelioService;
use App\Services\LocationAccessService;
use App\Services\TransactionService;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class ProcessJubelioOrder
{
    public function __construct(
        private TransactionService $transactionService,
        private JubelioService $jubelioService,
        private LocationAccessService $locationAccessService,
    ) {}

    /**
     * @return array{success: bool, message: string}
     */
    public function execute(Jubelioorder $order, ?int $executedByUserId = null): array
    {
        Log::info("Memproses Jubelioorder ID: {$order->id}, Type: {$order->type}, Invoice: {$order->invoice}");

        $order->refresh();
        $runCount = $order->run_count + 1;
        $dataApi = $this->resolvePayload($order);

        if ($dataApi === []) {
            $order->update([
                'run_count' => $runCount,
                'error_type' => 3,
                'error' => 'Payload JSON tidak valid',
                'status' => 1,
            ]);

            return ['success' => false, 'message' => 'Payload JSON tidak valid'];
        }

        if ($order->type === 'SELL') {
            return $this->processSell($order, $dataApi, $runCount, $executedByUserId);
        }

        if ($order->type === 'RETURN') {
            return $this->processReturn($order, $dataApi, $runCount, $executedByUserId);
        }

        return ['success' => false, 'message' => 'Tipe order tidak didukung'];
    }

    /**
     * @return array<string, mixed>
     */
    protected function resolvePayload(Jubelioorder $order): array
    {
        if ((int) $order->source === 1) {
            return $order->payloadArray();
        }

        $fetched = $this->jubelioService->fetchSalesOrder($order->jubelio_order_id);
        if (! $fetched) {
            return [];
        }

        $order->update(['payload' => json_encode($fetched)]);

        return $fetched;
    }

    /**
     * @param  array<string, mixed>  $dataApi
     * @return array{success: bool, message: string}
     */
    protected function processSell(Jubelioorder $order, array $dataApi, int $runCount, ?int $executedByUserId): array
    {
        $jubelioSync = Jubeliosync::where('jubelio_store_id', $dataApi['store_id'])
            ->where('jubelio_location_id', $dataApi['location_id'])
            ->first();

        if (! $jubelioSync) {
            $order->update([
                'run_count' => $runCount,
                'error_type' => 1,
                'error' => 'Data sync store/location ID tidak ditemukan',
                'status' => 1,
            ]);

            return ['success' => false, 'message' => 'Data sync store/location ID tidak ditemukan'];
        }

        $matched = $this->matchItems($dataApi['items'] ?? [], 'qty');

        if ($matched['error']) {
            $order->update([
                'run_count' => $runCount,
                'error_type' => 1,
                'error' => $matched['error'],
                'status' => 1,
            ]);

            return ['success' => false, 'message' => $matched['error']];
        }

        $arrayInvoice = $dataApi['salesorder_no'] ?? $order->invoice;

        if (Transaction::where('type', Transaction::TYPE_SELL)->where('invoice_number', $arrayInvoice)->exists()) {
            $order->update([
                'run_count' => $runCount,
                'error_type' => 2,
                'error' => 'Transaction sudah ada',
                'status' => 2,
            ]);

            return ['success' => false, 'message' => 'Transaction sudah ada'];
        }

        $adjust = $dataApi['sub_total'] - $dataApi['grand_total'];
        $createData = $this->createTransaction(Transaction::TYPE_SELL, (object) [
            'date' => $dataApi['transaction_date'] ?? now()->toDateString(),
            'warehouse' => $jubelioSync->warehouse_id,
            'customer' => $jubelioSync->customer_id,
            'invoice' => $arrayInvoice,
            'note' => $executedByUserId ? 'generated manually from aria' : 'generated by cron aria',
            'account' => '7204',
            'addMoreInputFields' => $matched['items'],
            'disc' => '0',
            'adjustment' => $this->toggleSign($adjust),
            'ongkir' => '0',
        ]);

        if ($createData['status'] === '200') {
            $order->update([
                'run_count' => $runCount,
                'error_type' => 10,
                'error' => null,
                'status' => 2,
                'execute_by' => $executedByUserId ?? 0,
            ]);
            Log::info("Berhasil Sell: {$arrayInvoice}");

            return ['success' => true, 'message' => 'Transaksi berhasil dibuat'];
        }

        $order->update([
            'run_count' => $runCount,
            'error_type' => 1,
            'error' => $createData['message'],
            'status' => 1,
        ]);

        return ['success' => false, 'message' => $createData['message']];
    }

    /**
     * @param  array<string, mixed>  $dataApi
     * @return array{success: bool, message: string}
     */
    protected function processReturn(Jubelioorder $order, array $dataApi, int $runCount, ?int $executedByUserId): array
    {
        $cekTransaksiSell = Transaction::where('type', Transaction::TYPE_SELL)
            ->where('invoice_number', $dataApi['salesorder_no'])
            ->first();

        if (! $cekTransaksiSell) {
            $order->update([
                'run_count' => $runCount,
                'error_type' => 3,
                'error' => 'Transaksi jual (asal) tidak ditemukan untuk retur ini',
                'status' => 1,
            ]);

            return ['success' => false, 'message' => 'Transaksi jual (asal) tidak ditemukan untuk retur ini'];
        }

        $matched = $this->matchItems($dataApi['items'] ?? [], 'qty_in_base');

        if ($matched['error']) {
            $order->update([
                'run_count' => $runCount,
                'error_type' => 1,
                'error' => $matched['error'],
                'status' => 1,
            ]);

            return ['success' => false, 'message' => $matched['error']];
        }

        if (Transaction::where('type', Transaction::TYPE_RETURN)->where('invoice_number', $dataApi['return_no'])->exists()) {
            $order->update([
                'run_count' => $runCount,
                'error_type' => 2,
                'error' => 'Invoice Retur sudah ada',
                'status' => 2,
            ]);

            return ['success' => false, 'message' => 'Invoice Retur sudah ada'];
        }

        $jubelioSync = Jubeliosync::where('jubelio_store_id', $dataApi['store_id'])
            ->where('jubelio_location_id', $dataApi['location_id'])
            ->first();

        if (! $jubelioSync) {
            $order->update([
                'run_count' => $runCount,
                'error_type' => 1,
                'error' => 'Data sync store/location ID untuk return tidak ditemukan',
                'status' => 1,
            ]);

            return ['success' => false, 'message' => 'Data sync store/location ID untuk return tidak ditemukan'];
        }

        $adjust = $dataApi['sub_total'] - $dataApi['grand_total'];
        $createData = $this->createTransaction(Transaction::TYPE_RETURN, (object) [
            'date' => $dataApi['transaction_date'] ?? now()->toDateString(),
            'warehouse' => $jubelioSync->warehouse_id,
            'customer' => $jubelioSync->customer_id,
            'invoice' => $dataApi['return_no'],
            'description' => $dataApi['salesorder_no'],
            'note' => $executedByUserId ? 'generated manually from aria' : 'generated by jubelio',
            'account' => '7204',
            'addMoreInputFields' => $matched['items'],
            'disc' => '0',
            'adjustment' => $this->toggleSign($adjust),
            'ongkir' => '0',
        ]);

        if ($createData['status'] === '200') {
            $order->update([
                'run_count' => $runCount,
                'error_type' => 10,
                'error' => null,
                'status' => 2,
                'execute_by' => $executedByUserId ?? 0,
            ]);
            Log::info('Berhasil Return: '.$dataApi['return_no']);

            return ['success' => true, 'message' => 'Transaksi retur berhasil dibuat'];
        }

        $order->update([
            'run_count' => $runCount,
            'error_type' => 1,
            'error' => $createData['message'],
            'status' => 1,
        ]);

        return ['success' => false, 'message' => $createData['message']];
    }

    /**
     * @param  list<array<string, mixed>>  $arrayItems
     * @return array{error: ?string, items: list<array<string, mixed>>}
     */
    protected function matchItems(array $arrayItems, string $qtyKey): array
    {
        $itemCodes = collect($arrayItems)->pluck('item_code')->unique()->all();
        $existingProducts = Item::findManyBySkus($itemCodes);

        $groupedData = collect($arrayItems)->partition(
            fn ($item) => isset($existingProducts[strtoupper($item['item_code'])])
        );

        $notMatched = $groupedData[1];

        if ($notMatched->count() > 0) {
            return [
                'error' => 'SKU tidak ditemukan: '.implode(', ', $notMatched->pluck('item_code')->toArray()),
                'items' => [],
            ];
        }

        $items = $groupedData[0]->map(function ($item) use ($existingProducts, $qtyKey) {
            $product = $existingProducts[strtoupper($item['item_code'])];
            $qty = $item[$qtyKey];

            return [
                'itemId' => $product->id,
                'code' => $product->code,
                'name' => $product->name,
                'quantity' => $qty,
                'price' => $item['price'],
                'discount' => 0,
                'subtotal' => $qty * $item['price'],
            ];
        })->values()->all();

        return ['error' => null, 'items' => $items];
    }

    protected function toggleSign(float|int $value): float|int
    {
        return -$value;
    }

    /**
     * @return array{status: string, message: string, transaction_id?: int}
     */
    protected function createTransaction(int $type, object $dataJubelio): array
    {
        try {
            return DB::transaction(function () use ($type, $dataJubelio) {
                $customer = Addrbook::find($dataJubelio->customer);
                $warehouse = Addrbook::find($dataJubelio->warehouse);

                if (! $customer || ! $warehouse) {
                    throw new \Exception('Customer or Warehouse not found.');
                }

                $this->locationAccessService->ensureJubelioPartyLocations($warehouse, $customer);

                $transaction = new Transaction;
                $transaction->date = Carbon::parse($dataJubelio->date);
                $transaction->type = $type;
                $transaction->adjustment = $dataJubelio->adjustment;
                $transaction->user_id = null;
                $transaction->submit_type = Transaction::SUBMIT_TYPE_JUBELIO;
                $transaction->description = $dataJubelio->description ?? '';
                $transaction->notes = $dataJubelio->note ?? '';
                $transaction->invoice_number = $dataJubelio->invoice;
                $transaction->due_date = null;
                $transaction->status = Transaction::STATUS_COMPLETED;

                if ($type === Transaction::TYPE_RETURN) {
                    $transaction->sender_id = $customer->id;
                    $transaction->sender_type = $customer->type;
                    $transaction->receiver_id = $warehouse->id;
                    $transaction->receiver_type = $warehouse->type;
                } else {
                    $transaction->sender_id = $warehouse->id;
                    $transaction->sender_type = $warehouse->type;
                    $transaction->receiver_id = $customer->id;
                    $transaction->receiver_type = $customer->type;
                }

                $transaction->save();

                $totalQty = 0;
                $subTotal = 0;

                foreach ($dataJubelio->addMoreInputFields as $item) {
                    TransactionDetail::create([
                        'transaction_id' => $transaction->id,
                        'date' => $transaction->date,
                        'transaction_type' => $type,
                        'sender_id' => $transaction->sender_id,
                        'receiver_id' => $transaction->receiver_id,
                        'item_id' => $item['itemId'],
                        'quantity' => $item['quantity'],
                        'price' => $item['price'],
                        'discount' => 0,
                        'total' => $item['subtotal'],
                    ]);
                    $totalQty += $item['quantity'];
                    $subTotal += $item['subtotal'];
                }

                $transaction->total = $subTotal;
                $grandTotal = $subTotal + $transaction->adjustment;
                $transaction->grand_total = ($type === Transaction::TYPE_SELL) ? -$grandTotal : $grandTotal;
                $transaction->total_items = $totalQty;
                $transaction->save();

                $this->transactionService->handleTransaction($transaction);

                return [
                    'status' => '200',
                    'message' => 'ok',
                    'transaction_id' => $transaction->id,
                ];
            });
        } catch (\Exception $e) {
            return [
                'status' => '422',
                'message' => $e->getMessage(),
            ];
        }
    }
}
