<?php

use App\Support\ObsoleteReportPermissions;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    public function up(): void
    {
        ObsoleteReportPermissions::remove();
    }

    public function down(): void
    {
        // Leftover names are not regenerated by PermissionGenerator.
    }
};
