<?php

namespace App\Support;

use App\Models\Addrbook;

class SidebarFavoriteRegistry
{
    /**
     * Sidebar pages that can be saved as favorites.
     *
     * Each entry:
     * - key: stable identifier stored in user preferences
     * - label: display name in sidebar / settings
     * - group: settings UI grouping
     * - permission: Spatie permission required (null = any authenticated user)
     * - route: Laravel route name
     * - params: route parameters
     * - active_prefix: URL prefix for active-state highlighting
     * - superadmin_only: visible only to user id 1
     *
     * @return list<array{key: string, label: string, group: string, permission: ?string, route: string, params: array<string, mixed>, active_prefix: string, superadmin_only?: bool}>
     */
    public static function links(): array
    {
        $links = [
            [
                'key' => 'dashboard',
                'label' => 'Dashboard',
                'group' => 'General',
                'permission' => null,
                'route' => 'dashboard',
                'params' => [],
                'active_prefix' => '/dashboard',
            ],
            [
                'key' => 'transactions-list',
                'label' => 'List All',
                'group' => 'Transactions',
                'permission' => 'transactions-list',
                'route' => 'transactions.index',
                'params' => [],
                'active_prefix' => '/transactions',
            ],
            [
                'key' => 'transactions-buy',
                'label' => 'Buy',
                'group' => 'Transactions',
                'permission' => 'transactions-type-buy',
                'route' => 'transactions.create',
                'params' => ['type' => 'buy'],
                'active_prefix' => '/transactions/buy',
            ],
            [
                'key' => 'transactions-sell',
                'label' => 'Sell',
                'group' => 'Transactions',
                'permission' => 'transactions-type-sell',
                'route' => 'transactions.create',
                'params' => ['type' => 'sell'],
                'active_prefix' => '/transactions/sell',
            ],
            [
                'key' => 'transactions-move',
                'label' => 'Move',
                'group' => 'Transactions',
                'permission' => 'transactions-type-move',
                'route' => 'transactions.create',
                'params' => ['type' => 'move'],
                'active_prefix' => '/transactions/move',
            ],
            [
                'key' => 'transactions-cash-in',
                'label' => 'Cash In',
                'group' => 'Transactions',
                'permission' => 'transactions-type-cash-in',
                'route' => 'transactions.cash-in',
                'params' => [],
                'active_prefix' => '/transactions/cash-in',
            ],
            [
                'key' => 'transactions-cash-out',
                'label' => 'Cash Out',
                'group' => 'Transactions',
                'permission' => 'transactions-type-cash-out',
                'route' => 'transactions.cash-out',
                'params' => [],
                'active_prefix' => '/transactions/cash-out',
            ],
            [
                'key' => 'transactions-transfer',
                'label' => 'Transfer',
                'group' => 'Transactions',
                'permission' => 'transactions-type-transfer',
                'route' => 'transactions.transfer',
                'params' => [],
                'active_prefix' => '/transactions/transfer',
            ],
            [
                'key' => 'transactions-adjust',
                'label' => 'Adjust',
                'group' => 'Transactions',
                'permission' => 'transactions-type-adjust',
                'route' => 'transactions.adjust',
                'params' => [],
                'active_prefix' => '/transactions/adjust',
            ],
            [
                'key' => 'transactions-return',
                'label' => 'Return',
                'group' => 'Transactions',
                'permission' => 'transactions-type-return',
                'route' => 'transactions.create',
                'params' => ['type' => 'return'],
                'active_prefix' => '/transactions/return/',
            ],
            [
                'key' => 'transactions-return-supplier',
                'label' => 'Return Supplier',
                'group' => 'Transactions',
                'permission' => 'transactions-type-return-supplier',
                'route' => 'transactions.create',
                'params' => ['type' => 'return-supplier'],
                'active_prefix' => '/transactions/return-supplier/',
            ],
            [
                'key' => 'report-export-sell',
                'label' => 'Export Sell',
                'group' => 'Transactions',
                'permission' => 'report-export-sell',
                'route' => 'transactions.export-sell',
                'params' => [],
                'active_prefix' => '/transactions/export-sell',
            ],
            [
                'key' => 'invoice-maker',
                'label' => 'Invoice Maker',
                'group' => 'Invoice',
                'permission' => 'invoice-maker-list',
                'route' => 'invoice-maker.index',
                'params' => [],
                'active_prefix' => '/invoice-maker',
            ],
            [
                'key' => 'items-list',
                'label' => 'Item',
                'group' => 'Stuff',
                'permission' => 'items-list',
                'route' => 'items.index',
                'params' => [],
                'active_prefix' => '/items',
            ],
            [
                'key' => 'assetlancar-list',
                'label' => 'Asset Lancar',
                'group' => 'Stuff',
                'permission' => 'assetLancar-list',
                'route' => 'assetlancar.index',
                'params' => [],
                'active_prefix' => '/assetlancar',
            ],
            [
                'key' => 'assettetap-list',
                'label' => 'Asset Tetap',
                'group' => 'Stuff',
                'permission' => 'assetTetap-list',
                'route' => 'assettetap.index',
                'params' => [],
                'active_prefix' => '/assettetap',
            ],
            [
                'key' => 'stuff-group-list',
                'label' => 'Group',
                'group' => 'Stuff',
                'permission' => 'stuff-group-list',
                'route' => 'items.group',
                'params' => [],
                'active_prefix' => '/items-group',
            ],
            [
                'key' => 'stuff-tag-list',
                'label' => 'Tags',
                'group' => 'Stuff',
                'permission' => 'stuff-tag-list',
                'route' => 'tags.index',
                'params' => [],
                'active_prefix' => '/tags',
            ],
            [
                'key' => 'restock-list',
                'label' => 'Restock',
                'group' => 'Stuff',
                'permission' => 'restock-list',
                'route' => 'restock.index',
                'params' => [],
                'active_prefix' => '/restock',
            ],
            [
                'key' => 'items-legacy-converter',
                'label' => 'Legacy Converter',
                'group' => 'Stuff',
                'permission' => 'items-convert-legacy',
                'route' => 'items.legacy-converter',
                'params' => [],
                'active_prefix' => '/items/legacy-converter',
            ],
            [
                'key' => 'stock-notification-list',
                'label' => 'Stock Alerts',
                'group' => 'Stuff',
                'permission' => 'stock-notification-list',
                'route' => 'stock-notifications.index',
                'params' => [],
                'active_prefix' => '/stock-notifications',
            ],
            [
                'key' => 'report-warehouse-item',
                'label' => 'Item Gudang',
                'group' => 'Reports',
                'permission' => 'report-warehouse-item',
                'route' => 'reports.warehouse-item',
                'params' => [],
                'active_prefix' => '/reports/warehouse-item',
            ],
            [
                'key' => 'report-warehouse-arrangement',
                'label' => 'Warehouse Arrangement',
                'group' => 'Reports',
                'permission' => 'report-warehouse-arrangement',
                'route' => 'reports.warehouse-arrangement',
                'params' => [],
                'active_prefix' => '/reports/warehouse-arrangement',
            ],
            [
                'key' => 'report-product-performance',
                'label' => 'Product Performance',
                'group' => 'Reports',
                'permission' => 'report-product-performance',
                'route' => 'reports.product-performance',
                'params' => [],
                'active_prefix' => '/reports/product-performance',
            ],
            [
                'key' => 'report-inventory-health',
                'label' => 'Inventory Health',
                'group' => 'Reports',
                'permission' => 'report-inventory-health',
                'route' => 'reports.inventory-health',
                'params' => [],
                'active_prefix' => '/reports/inventory-health',
            ],
            [
                'key' => 'report-nett-cash',
                'label' => 'Nett Cash',
                'group' => 'Reports',
                'permission' => 'report-nett-cash',
                'route' => 'reports.nett-cash-sby',
                'params' => [],
                'active_prefix' => '/reports/nett-cash-sby',
            ],
            [
                'key' => 'report-neraca',
                'label' => 'Neraca',
                'group' => 'Reports',
                'permission' => 'report-neraca',
                'route' => 'reports.neraca',
                'params' => [],
                'active_prefix' => '/reports/neraca',
            ],
            [
                'key' => 'report-laba-rugi',
                'label' => 'Laba Rugi',
                'group' => 'Reports',
                'permission' => 'report-laba-rugi',
                'route' => 'reports.laba-rugi',
                'params' => [],
                'active_prefix' => '/reports/laba-rugi',
            ],
            [
                'key' => 'report-channel-pnl',
                'label' => 'Channel P&L',
                'group' => 'Reports',
                'permission' => 'report-channel-pnl',
                'route' => 'reports.channel-pnl',
                'params' => [],
                'active_prefix' => '/reports/channel-pnl',
            ],
            [
                'key' => 'report-receivables',
                'label' => 'Piutang Usaha',
                'group' => 'Reports',
                'permission' => 'report-receivables',
                'route' => 'reports.receivables',
                'params' => [],
                'active_prefix' => '/reports/receivables',
            ],
            [
                'key' => 'report-payables',
                'label' => 'Hutang Usaha',
                'group' => 'Reports',
                'permission' => 'report-payables',
                'route' => 'reports.payables',
                'params' => [],
                'active_prefix' => '/reports/payables',
            ],
            [
                'key' => 'report-asset-tetap',
                'label' => 'Nilai Buku Asset Tetap',
                'group' => 'Reports',
                'permission' => 'report-asset-tetap',
                'route' => 'reports.asset-tetap',
                'params' => [],
                'active_prefix' => '/reports/asset-tetap',
            ],
            [
                'key' => 'report-tax-ppn',
                'label' => 'Laporan PPN',
                'group' => 'Reports',
                'permission' => 'report-tax-ppn',
                'route' => 'reports.tax.ppn',
                'params' => [],
                'active_prefix' => '/reports/tax/ppn',
            ],
            [
                'key' => 'report-tax-pph',
                'label' => 'Laporan PPh Final',
                'group' => 'Reports',
                'permission' => 'report-tax-pph',
                'route' => 'reports.tax.pph',
                'params' => [],
                'active_prefix' => '/reports/tax/pph',
            ],
            [
                'key' => 'report-tax-faktur',
                'label' => 'Faktur Pajak',
                'group' => 'Reports',
                'permission' => 'report-tax-faktur',
                'route' => 'reports.tax.faktur.index',
                'params' => [],
                'active_prefix' => '/reports/tax/faktur',
            ],
            [
                'key' => 'report-produksi-potong',
                'label' => 'Statistik Potong',
                'group' => 'Reports',
                'permission' => 'report-produksi-potong',
                'route' => 'reports.produksi-potong',
                'params' => [],
                'active_prefix' => '/reports/produksi-potong',
            ],
            [
                'key' => 'report-produksi-qc',
                'label' => 'Statistik QC',
                'group' => 'Reports',
                'permission' => 'report-produksi-qc',
                'route' => 'reports.produksi-qc',
                'params' => [],
                'active_prefix' => '/reports/produksi-qc',
            ],
            [
                'key' => 'report-entities',
                'label' => 'Reporting Entities',
                'group' => 'Reports',
                'permission' => null,
                'route' => 'reports.entities.index',
                'params' => [],
                'active_prefix' => '/reports/entities',
                'superadmin_only' => true,
            ],
            [
                'key' => 'jubelio-orders',
                'label' => 'Jubelio Orders',
                'group' => 'Jubelio',
                'permission' => 'jubelio-view',
                'route' => 'jubelio.index',
                'params' => [],
                'active_prefix' => '/jubelio',
            ],
            [
                'key' => 'jubelio-cancellations',
                'label' => 'Jubelio Cancellations',
                'group' => 'Jubelio',
                'permission' => 'jubelio-view',
                'route' => 'jubelio.returns.index',
                'params' => [],
                'active_prefix' => '/jubelio-returns',
            ],
            [
                'key' => 'jubelio-get-orders',
                'label' => 'Get Orders',
                'group' => 'Jubelio',
                'permission' => 'jubelio-view',
                'route' => 'jubelio.get-orders.index',
                'params' => [],
                'active_prefix' => '/jubelio-get-orders',
            ],
            [
                'key' => 'jubelio-cek-order',
                'label' => 'Cek Order',
                'group' => 'Jubelio',
                'permission' => 'jubelio-view',
                'route' => 'jubelio.order.cek',
                'params' => [],
                'active_prefix' => '/jubelio/order/cek',
            ],
            [
                'key' => 'jubelio-koneksi',
                'label' => 'Koneksi',
                'group' => 'Jubelio',
                'permission' => 'jubelio-view',
                'route' => 'jubelio.token.index',
                'params' => [],
                'active_prefix' => '/jubelio/token',
            ],
            [
                'key' => 'jubelio-stock-sync',
                'label' => 'Stock Sync',
                'group' => 'Jubelio',
                'permission' => 'jubelio-sync',
                'route' => 'jubelio.transaction.sync',
                'params' => [],
                'active_prefix' => '/jubelio-transaction',
            ],
            [
                'key' => 'jubelio-warehouse-map',
                'label' => 'Warehouse Map',
                'group' => 'Jubelio',
                'permission' => 'jubelio-sync',
                'route' => 'jubelio.sync.index',
                'params' => [],
                'active_prefix' => '/jubelio-sync',
            ],
            [
                'key' => 'jubelio-stock-check',
                'label' => 'Stock Check',
                'group' => 'Jubelio',
                'permission' => 'jubelio-stock-check',
                'route' => 'jubelio-stock-checks.index',
                'params' => [],
                'active_prefix' => '/jubelio-stock-checks',
            ],
            [
                'key' => 'shopee-ads',
                'label' => 'Shopee Ads',
                'group' => 'Integrations',
                'permission' => 'shopee-ads-view',
                'route' => 'shopee-ads.index',
                'params' => [],
                'active_prefix' => '/shopee-ads',
            ],
            [
                'key' => 'journal-accounts',
                'label' => 'Journal Accounts',
                'group' => 'Journals',
                'permission' => 'journal-account-list',
                'route' => 'account-list.index',
                'params' => [],
                'active_prefix' => '/journals/account-list',
            ],
            [
                'key' => 'journal-operations',
                'label' => 'Journal Operations',
                'group' => 'Journals',
                'permission' => 'journal-operation-list',
                'route' => 'operations.index',
                'params' => [],
                'active_prefix' => '/journals/operations',
            ],
            [
                'key' => 'production-list',
                'label' => 'Production',
                'group' => 'Produksi',
                'permission' => 'production-list',
                'route' => 'produksi.index',
                'params' => [],
                'active_prefix' => '/produksi',
            ],
            [
                'key' => 'production-setoran',
                'label' => 'Setoran',
                'group' => 'Produksi',
                'permission' => 'production-setoran-list',
                'route' => 'produksi.setoran.index',
                'params' => [],
                'active_prefix' => '/produksi/setoran',
            ],
            [
                'key' => 'production-potong',
                'label' => 'Potong Workers',
                'group' => 'Produksi',
                'permission' => 'production-worker-list',
                'route' => 'produksi.potong.index',
                'params' => [],
                'active_prefix' => '/produksi/potong',
            ],
            [
                'key' => 'production-jahit',
                'label' => 'Jahit Workers',
                'group' => 'Produksi',
                'permission' => 'production-worker-list',
                'route' => 'produksi.jahit.index',
                'params' => [],
                'active_prefix' => '/produksi/jahit',
            ],
            [
                'key' => 'production-qc',
                'label' => 'QC Workers',
                'group' => 'Produksi',
                'permission' => 'production-worker-list',
                'route' => 'produksi.qc.index',
                'params' => [],
                'active_prefix' => '/produksi/qc',
            ],
            [
                'key' => 'production-pritil',
                'label' => 'Pritil Workers',
                'group' => 'Produksi',
                'permission' => 'production-worker-list',
                'route' => 'produksi.pritil.index',
                'params' => [],
                'active_prefix' => '/produksi/pritil',
            ],
            [
                'key' => 'borongan-list',
                'label' => 'Borongan',
                'group' => 'Produksi',
                'permission' => 'borongan-list',
                'route' => 'borongan.index',
                'params' => [],
                'active_prefix' => '/borongan',
            ],
            [
                'key' => 'setting-general',
                'label' => 'General Settings',
                'group' => 'System',
                'permission' => 'setting-general-view',
                'route' => 'system-settings.index',
                'params' => [],
                'active_prefix' => '/system-settings',
            ],
            [
                'key' => 'setting-cron-manager',
                'label' => 'Cron Manager',
                'group' => 'System',
                'permission' => 'setting-cron-manager-view',
                'route' => 'scheduled-tasks.index',
                'params' => [],
                'active_prefix' => '/cron-manager',
            ],
            [
                'key' => 'warehouse-stat-backfill',
                'label' => 'Warehouse Stats Backfill',
                'group' => 'System',
                'permission' => 'report-warehouse-arrangement',
                'route' => 'warehouse-stat-backfill.index',
                'params' => [],
                'active_prefix' => '/warehouse-stat-backfill',
            ],
            [
                'key' => 'users-list',
                'label' => 'Users',
                'group' => 'User Management',
                'permission' => 'users-list',
                'route' => 'users.index',
                'params' => [],
                'active_prefix' => '/users',
            ],
            [
                'key' => 'users-roles-list',
                'label' => 'Roles',
                'group' => 'User Management',
                'permission' => 'users-roles-list',
                'route' => 'roles.index',
                'params' => [],
                'active_prefix' => '/roles',
            ],
            [
                'key' => 'users-permissions-list',
                'label' => 'Permissions',
                'group' => 'User Management',
                'permission' => 'users-permissions-list',
                'route' => 'permissions.index',
                'params' => [],
                'active_prefix' => '/permissions',
            ],
            [
                'key' => 'users-locations-list',
                'label' => 'Locations',
                'group' => 'User Management',
                'permission' => 'users-locations-list',
                'route' => 'locations.index',
                'params' => [],
                'active_prefix' => '/locations',
            ],
            [
                'key' => 'users-staff-roles-view',
                'label' => 'Checklist Peran',
                'group' => 'User Management',
                'permission' => 'users-staff-roles-view',
                'route' => 'staff-checklists.index',
                'params' => [],
                'active_prefix' => '/staff-checklists',
            ],
            [
                'key' => 'checklist-templates-edit',
                'label' => 'Template Checklist',
                'group' => 'User Management',
                'permission' => 'users-staff-roles-view',
                'route' => 'staff-checklists.templates.index',
                'params' => [],
                'active_prefix' => '/staff-checklists/templates',
            ],
        ];

        foreach (Addrbook::getTypes() as $type) {
            $links[] = [
                'key' => 'addrbook-'.$type['slug'],
                'label' => $type['name'],
                'group' => 'Address Book',
                'permission' => Addrbook::getPermissions($type['slug'])['view'],
                'route' => 'addrbook.type.index',
                'params' => ['type' => $type['slug']],
                'active_prefix' => '/'.$type['slug'],
            ];
        }

        return $links;
    }

    /**
     * @return array<string, array{key: string, label: string, group: string, permission: ?string, route: string, params: array<string, mixed>, active_prefix: string, superadmin_only?: bool}>
     */
    public static function keyed(): array
    {
        $keyed = [];
        foreach (self::links() as $link) {
            $keyed[$link['key']] = $link;
        }

        return $keyed;
    }
}
